version: "3.8"

services:
  my-app:
    image: cr.yandex/${REGISTRY_ID}/tmp:latest
    build:
      context: .
    environment:
      env_file:
        .env
    ports:
      - "${PORT:-3000}:3000"
    restart: always
    networks:
      - awesome
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    volumes:
      - ./data/nginx/core/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/logs/:/var/log/nginx/
      - ./data/certbot:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    depends_on:
     - my-app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - awesome
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

networks:
  awesome:
    driver: bridge
